import { State, City, LocalityInfo, Landmark } from '../types';

export const INDIAN_STATES: State[] = [
  { id: 'up', name: 'Uttar Pradesh', code: 'UP', slug: 'uttar-pradesh' },
  { id: 'dl', name: 'Delhi', code: 'DL', slug: 'delhi' },
  { id: 'mh', name: 'Maharashtra', code: 'MH', slug: 'maharashtra' },
  { id: 'ka', name: 'Karnataka', code: 'KA', slug: 'karnataka' },
  { id: 'ts', name: 'Telangana', code: 'TS', slug: 'telangana' },
  { id: 'wb', name: 'West Bengal', code: 'WB', slug: 'west-bengal' },
  { id: 'rj', name: 'Rajasthan', code: 'RJ', slug: 'rajasthan' },
  { id: 'hr', name: 'Haryana', code: 'HR', slug: 'haryana' },
  { id: 'br', name: 'Bihar', code: 'BR', slug: 'bihar' },
  { id: 'mp', name: 'Madhya Pradesh', code: 'MP', slug: 'madhya-pradesh' },
  { id: 'gj', name: 'Gujarat', code: 'GJ', slug: 'gujarat' },
  { id: 'tn', name: 'Tamil Nadu', code: 'TN', slug: 'tamil-nadu' },
  { id: 'pb', name: 'Punjab', code: 'PB', slug: 'punjab' },
  { id: 'ch', name: 'Chandigarh', code: 'CH', slug: 'chandigarh' },
  { id: 'uk', name: 'Uttarakhand', code: 'UK', slug: 'uttarakhand' },
];

export const INDIAN_CITIES: City[] = [
  {
    id: 'prayagraj',
    name: 'Prayagraj',
    slug: 'prayagraj',
    state_code: 'UP',
    state_name: 'Uttar Pradesh',
    latitude: 25.4358,
    longitude: 81.8463,
    is_popular: true,
    image_url: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80',
    popular_for: 'Allahabad University, Civil Services & Judiciary Hub',
    active_listings_count: 10,
  },
  {
    id: 'lucknow',
    name: 'Lucknow',
    slug: 'lucknow',
    state_code: 'UP',
    state_name: 'Uttar Pradesh',
    latitude: 26.8467,
    longitude: 80.9462,
    is_popular: true,
    image_url: 'https://images.unsplash.com/photo-1596178065887-1198b6148b2b?auto=format&fit=crop&w=800&q=80',
    popular_for: 'Capital City, Medical, Engineering & IT Hub',
    active_listings_count: 5,
  },
  {
    id: 'delhi',
    name: 'Delhi / NCR',
    slug: 'delhi',
    state_code: 'DL',
    state_name: 'Delhi',
    latitude: 28.6139,
    longitude: 77.2090,
    is_popular: true,
    image_url: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80',
    popular_for: 'UPSC Aspirants, DU Colleges, Startups & Corporates',
    active_listings_count: 6,
  },
  {
    id: 'mumbai',
    name: 'Mumbai',
    slug: 'mumbai',
    state_code: 'MH',
    state_name: 'Maharashtra',
    latitude: 19.0760,
    longitude: 72.8777,
    is_popular: true,
    image_url: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=800&q=80',
    popular_for: 'Financial Capital, Media, IIT Bombay & Universities',
    active_listings_count: 4,
  },
  {
    id: 'bengaluru',
    name: 'Bengaluru',
    slug: 'bengaluru',
    state_code: 'KA',
    state_name: 'Karnataka',
    latitude: 12.9716,
    longitude: 77.5946,
    is_popular: true,
    image_url: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=800&q=80',
    popular_for: 'Silicon Valley of India, Engineering & Startups',
    active_listings_count: 4,
  },
  {
    id: 'pune',
    name: 'Pune',
    slug: 'pune',
    state_code: 'MH',
    state_name: 'Maharashtra',
    latitude: 18.5204,
    longitude: 73.8567,
    is_popular: true,
    image_url: 'https://images.unsplash.com/photo-1625480876272-d5a2d718ec49?auto=format&fit=crop&w=800&q=80',
    popular_for: 'Oxford of the East, Tech Hub, Student Friendly',
    active_listings_count: 0,
  },
  {
    id: 'varanasi',
    name: 'Varanasi',
    slug: 'varanasi',
    state_code: 'UP',
    state_name: 'Uttar Pradesh',
    latitude: 25.3176,
    longitude: 82.9739,
    is_popular: true,
    image_url: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80',
    popular_for: 'BHU University Campus, Cultural Hub & Coaching',
    active_listings_count: 0,
  },
  {
    id: 'jaipur',
    name: 'Jaipur',
    slug: 'jaipur',
    state_code: 'RJ',
    state_name: 'Rajasthan',
    latitude: 26.9124,
    longitude: 75.7873,
    is_popular: true,
    image_url: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=800&q=80',
    popular_for: 'Rajasthan University, Coaching Institutes & Culture',
    active_listings_count: 0,
  },
  {
    id: 'hyderabad',
    name: 'Hyderabad',
    slug: 'hyderabad',
    state_code: 'TS',
    state_name: 'Telangana',
    latitude: 17.3850,
    longitude: 78.4867,
    is_popular: true,
    image_url: 'https://images.unsplash.com/photo-1605007493699-ce65834f8a00?auto=format&fit=crop&w=800&q=80',
    popular_for: 'HITEC City, Osmania University, Pharma & Tech Hub',
    active_listings_count: 0,
  },
  {
    id: 'kolkata',
    name: 'Kolkata',
    slug: 'kolkata',
    state_code: 'WB',
    state_name: 'West Bengal',
    latitude: 22.5726,
    longitude: 88.3639,
    is_popular: true,
    image_url: 'https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=800&q=80',
    popular_for: 'Jadavpur, Calcutta University, Salt Lake Tech Center',
    active_listings_count: 0,
  },
  {
    id: 'noida',
    name: 'Noida',
    slug: 'noida',
    state_code: 'UP',
    state_name: 'Uttar Pradesh',
    latitude: 28.5355,
    longitude: 77.3910,
    is_popular: true,
    image_url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    popular_for: 'IT Hub, Amity University, Sector 62 Educational Hub',
    active_listings_count: 0,
  },
  {
    id: 'gurugram',
    name: 'Gurugram',
    slug: 'gurugram',
    state_code: 'HR',
    state_name: 'Haryana',
    latitude: 28.4595,
    longitude: 77.0266,
    is_popular: true,
    image_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    popular_for: 'Cyber City, Corporate Headquarters & Modern PGs',
    active_listings_count: 0,
  },
];

export const INDIAN_LOCALITIES: LocalityInfo[] = [
  // --- PRAYAGRAJ (UP) ---
  {
    id: 'katra',
    name: 'Katra',
    slug: 'katra',
    city_slug: 'prayagraj',
    city_name: 'Prayagraj',
    state_code: 'UP',
    state_name: 'Uttar Pradesh',
    hindi_name: 'कटरा',
    latitude: 25.4563,
    longitude: 81.8546,
    description: 'Primary student epicenter with book markets and budget rooms within walking distance of Allahabad University.',
    popular_for: 'Student PGs, University Access, Affordable Food',
    active_listings_count: 4,
    average_rent: 4800,
    landmark_highlight: 'Near AU Library Gate & Katra Chauraha',
  },
  {
    id: 'civil-lines-prayagraj',
    name: 'Civil Lines',
    slug: 'civil-lines',
    city_slug: 'prayagraj',
    city_name: 'Prayagraj',
    state_code: 'UP',
    state_name: 'Uttar Pradesh',
    hindi_name: 'सिविल लाइंस',
    latitude: 25.4484,
    longitude: 81.8331,
    description: 'Modern, upscale center featuring premium PGs, furnished flats, cafes, and major civil services coaching centers.',
    popular_for: 'Premium PGs, IAS/PCS Coaching, Connectivity',
    active_listings_count: 2,
    average_rent: 7500,
    landmark_highlight: 'Near Subhash Chauraha & Cathedral',
  },
  {
    id: 'mumfordganj',
    name: 'Mumfordganj',
    slug: 'mumfordganj',
    city_slug: 'prayagraj',
    city_name: 'Prayagraj',
    state_code: 'UP',
    state_name: 'Uttar Pradesh',
    hindi_name: 'ममफोर्डगंज',
    latitude: 25.4678,
    longitude: 81.8492,
    description: 'Peaceful residential locality favored by civil service aspirants for quiet study environments.',
    popular_for: 'Quiet Study Atmosphere, Independent Rooms',
    active_listings_count: 1,
    average_rent: 5500,
    landmark_highlight: 'Near Azad Park North Gate',
  },
  {
    id: 'george-town',
    name: 'George Town',
    slug: 'george-town',
    city_slug: 'prayagraj',
    city_name: 'Prayagraj',
    state_code: 'UP',
    state_name: 'Uttar Pradesh',
    hindi_name: 'जॉर्ज टाउन',
    latitude: 25.4412,
    longitude: 81.8598,
    description: 'Centrally located neighborhood close to CMP Degree College and Medical College.',
    popular_for: 'CMP Degree College, Tree-lined Streets',
    active_listings_count: 1,
    average_rent: 5200,
    landmark_highlight: 'Near CMP College',
  },
  {
    id: 'university-area',
    name: 'University Area',
    slug: 'university-area',
    city_slug: 'prayagraj',
    city_name: 'Prayagraj',
    state_code: 'UP',
    state_name: 'Uttar Pradesh',
    hindi_name: 'विश्वविद्यालय क्षेत्र',
    latitude: 25.4595,
    longitude: 81.8601,
    description: 'Surrounds Allahabad University Senate House with high student concentration.',
    popular_for: 'University Gate Access, Student Messes',
    active_listings_count: 1,
    average_rent: 4200,
    landmark_highlight: 'AU Senate Hall',
  },
  {
    id: 'daraganj',
    name: 'Daraganj',
    slug: 'daraganj',
    city_slug: 'prayagraj',
    city_name: 'Prayagraj',
    state_code: 'UP',
    state_name: 'Uttar Pradesh',
    hindi_name: 'दारागंज',
    latitude: 25.4385,
    longitude: 81.8742,
    description: 'Riverside locality along the holy Ganga river with budget-friendly student accommodations.',
    popular_for: 'Budget Rooms, Traditional Atmosphere',
    active_listings_count: 1,
    average_rent: 3800,
    landmark_highlight: 'Near Shastri Bridge',
  },
  {
    id: 'tagore-town',
    name: 'Tagore Town',
    slug: 'tagore-town',
    city_slug: 'prayagraj',
    city_name: 'Prayagraj',
    state_code: 'UP',
    state_name: 'Uttar Pradesh',
    hindi_name: 'टैगोर टाउन',
    latitude: 25.4475,
    longitude: 81.8525,
    description: 'Prime central residential sector popular with coaching students.',
    popular_for: 'Coaching Hubs, Girls Hostels',
    active_listings_count: 0,
    average_rent: 5800,
    landmark_highlight: 'Tagore Town Chauraha',
  },
  {
    id: 'teliarganj',
    name: 'Teliarganj',
    slug: 'teliarganj',
    city_slug: 'prayagraj',
    city_name: 'Prayagraj',
    state_code: 'UP',
    state_name: 'Uttar Pradesh',
    hindi_name: 'तेलियरगंज',
    latitude: 25.4921,
    longitude: 81.8637,
    description: 'North Prayagraj educational hub adjoining MNNIT engineering campus.',
    popular_for: 'MNNIT Engineering Students, Tech PGs',
    active_listings_count: 0,
    average_rent: 5000,
    landmark_highlight: 'MNNIT Main Gate',
  },

  // --- LUCKNOW (UP) ---
  {
    id: 'gomti-nagar',
    name: 'Gomti Nagar',
    slug: 'gomti-nagar',
    city_slug: 'lucknow',
    city_name: 'Lucknow',
    state_code: 'UP',
    state_name: 'Uttar Pradesh',
    hindi_name: 'गोमती नगर',
    latitude: 26.8500,
    longitude: 80.9950,
    description: 'Premier planned residential & commercial sector with high-end flats, modern PGs, IT parks, and coaching institutes.',
    popular_for: 'IT Professionals, UPSC Coaching, Modern Gated Societies',
    active_listings_count: 3,
    average_rent: 7500,
    landmark_highlight: 'Near Patrakarpuram & Vibhuti Khand',
  },
  {
    id: 'aliganj',
    name: 'Aliganj',
    slug: 'aliganj',
    city_slug: 'lucknow',
    city_name: 'Lucknow',
    state_code: 'UP',
    state_name: 'Uttar Pradesh',
    hindi_name: 'अलीगंज',
    latitude: 26.8900,
    longitude: 80.9400,
    description: 'Major student coaching hub close to Lucknow University and engineering colleges.',
    popular_for: 'Coaching Centers, Student Messes, Budget PGs',
    active_listings_count: 2,
    average_rent: 5500,
    landmark_highlight: 'Near Kapoorthala & Engineering College',
  },
  {
    id: 'hazratganj',
    name: 'Hazratganj',
    slug: 'hazratganj',
    city_slug: 'lucknow',
    city_name: 'Lucknow',
    state_code: 'UP',
    state_name: 'Uttar Pradesh',
    hindi_name: 'हज़रतगंज',
    latitude: 26.8520,
    longitude: 80.9440,
    description: 'Heritage downtown of Lucknow with great connectivity, civil service academies, and metro access.',
    popular_for: 'Metro Connectivity, High Street, Coaching Hubs',
    active_listings_count: 0,
    average_rent: 8000,
    landmark_highlight: 'Near GPO & Metro Station',
  },
  {
    id: 'indira-nagar',
    name: 'Indira Nagar',
    slug: 'indira-nagar',
    city_slug: 'lucknow',
    city_name: 'Lucknow',
    state_code: 'UP',
    state_name: 'Uttar Pradesh',
    hindi_name: 'इंदिरा नगर',
    latitude: 26.8850,
    longitude: 80.9850,
    description: 'Large residential colony popular for quiet student rooms and safe accommodations.',
    popular_for: 'Quiet Study Atmosphere, Metro Access',
    active_listings_count: 0,
    average_rent: 6000,
    landmark_highlight: 'Near Bhootnath Market',
  },

  // --- DELHI (NCT) ---
  {
    id: 'laxmi-nagar',
    name: 'Laxmi Nagar',
    slug: 'laxmi-nagar',
    city_slug: 'delhi',
    city_name: 'Delhi / NCR',
    state_code: 'DL',
    state_name: 'Delhi',
    hindi_name: 'लक्ष्मी नगर',
    latitude: 28.6310,
    longitude: 77.2770,
    description: 'Nationwide hub for Chartered Accountancy (CA), CS, and UPSC coaching with thousands of affordable rooms.',
    popular_for: 'CA/CS Hub, Blue Line Metro, Vibrant Student Markets',
    active_listings_count: 3,
    average_rent: 6500,
    landmark_highlight: 'Near Laxmi Nagar Metro Gate 4',
  },
  {
    id: 'mukherjee-nagar',
    name: 'Mukherjee Nagar',
    slug: 'mukherjee-nagar',
    city_slug: 'delhi',
    city_name: 'Delhi / NCR',
    state_code: 'DL',
    state_name: 'Delhi',
    hindi_name: 'मुखर्जी नगर',
    latitude: 28.7100,
    longitude: 77.2150,
    description: 'India premier epicenter for UPSC Civil Services and SSC preparation in North Delhi.',
    popular_for: 'UPSC Aspirants, 24/7 Libraries, Hindi & English Medium PGs',
    active_listings_count: 2,
    average_rent: 8500,
    landmark_highlight: 'Near Batra Cinema Complex',
  },
  {
    id: 'north-campus-delhi',
    name: 'North Campus (GTB Nagar)',
    slug: 'north-campus',
    city_slug: 'delhi',
    city_name: 'Delhi / NCR',
    state_code: 'DL',
    state_name: 'Delhi',
    hindi_name: 'नॉर्थ कैंपस (जीटीबी नगर)',
    latitude: 28.6970,
    longitude: 77.2070,
    description: 'Heart of Delhi University student life surrounding Miranda House, St. Stephens, Hindu College, and SRCC.',
    popular_for: 'Delhi University, Student Cafes, Metro Connectivity',
    active_listings_count: 1,
    average_rent: 11000,
    landmark_highlight: 'Near GTB Nagar & Vishwavidyalaya Metro',
  },
  {
    id: 'karol-bagh',
    name: 'Karol Bagh (Old Rajinder Nagar)',
    slug: 'karol-bagh',
    city_slug: 'delhi',
    city_name: 'Delhi / NCR',
    state_code: 'DL',
    state_name: 'Delhi',
    hindi_name: 'करोल बाग',
    latitude: 28.6510,
    longitude: 77.1900,
    description: 'Premier UPSC civil services coaching hub housing major institutes like Vajiram, Vision, and Rau.',
    popular_for: 'UPSC Aspirants, Coaching Institutes, Library Culture',
    active_listings_count: 0,
    average_rent: 12000,
    landmark_highlight: 'Near Bada Bazar & Karol Bagh Metro',
  },

  // --- MUMBAI (MH) ---
  {
    id: 'andheri-west',
    name: 'Andheri West',
    slug: 'andheri-west',
    city_slug: 'mumbai',
    city_name: 'Mumbai',
    state_code: 'MH',
    state_name: 'Maharashtra',
    hindi_name: 'अंधेरी वेस्ट',
    latitude: 19.1360,
    longitude: 72.8290,
    description: 'Bustling western suburb popular for college students, media professionals, and shared studio flats with metro & local train transit.',
    popular_for: 'Bhavan College, Media Hub, Metro Line 1 & 2',
    active_listings_count: 2,
    average_rent: 14000,
    landmark_highlight: 'Near Lokhandwala & Infinity Mall',
  },
  {
    id: 'powai',
    name: 'Powai',
    slug: 'powai',
    city_slug: 'mumbai',
    city_name: 'Mumbai',
    state_code: 'MH',
    state_name: 'Maharashtra',
    hindi_name: 'पवई',
    latitude: 19.1176,
    longitude: 72.9060,
    description: 'Modern lakeside tech town surrounding IIT Bombay, Hiranandani, and premier startup hubs.',
    popular_for: 'IIT Bombay, Tech Startups, High Quality PGs',
    active_listings_count: 2,
    average_rent: 16000,
    landmark_highlight: 'Near IIT Bombay Main Gate',
  },
  {
    id: 'bandra-west',
    name: 'Bandra West',
    slug: 'bandra-west',
    city_slug: 'mumbai',
    city_name: 'Mumbai',
    state_code: 'MH',
    state_name: 'Maharashtra',
    hindi_name: 'बांद्रा वेस्ट',
    latitude: 19.0596,
    longitude: 72.8295,
    description: 'Queen of the Suburbs with premier colleges (St. Xavier, National College) and prime connectivity.',
    popular_for: 'Top Colleges, Cafes, Coastal Promenades',
    active_listings_count: 0,
    average_rent: 22000,
    landmark_highlight: 'Near Hill Road & Bandstand',
  },

  // --- BENGALURU (KA) ---
  {
    id: 'koramangala',
    name: 'Koramangala',
    slug: 'koramangala',
    city_slug: 'bengaluru',
    city_name: 'Bengaluru',
    state_code: 'KA',
    state_name: 'Karnataka',
    hindi_name: 'कोरमंगला',
    latitude: 12.9352,
    longitude: 77.6245,
    description: 'India startup capital neighborhood with Christ University, tech co-working spaces, and premium youth coliving spaces.',
    popular_for: 'Christ University, Startups, Premium Coliving',
    active_listings_count: 2,
    average_rent: 12000,
    landmark_highlight: 'Near Sony World Signal & Christ College',
  },
  {
    id: 'hsr-layout',
    name: 'HSR Layout',
    slug: 'hsr-layout',
    city_slug: 'bengaluru',
    city_name: 'Bengaluru',
    state_code: 'KA',
    state_name: 'Karnataka',
    hindi_name: 'एचएसआर लेआउट',
    latitude: 12.9121,
    longitude: 77.6446,
    description: 'Planned wide-street tech hub connecting Koramangala and Electronic City with modern student & professional flats.',
    popular_for: 'Tech Companies, Tree-lined Sectors, Safe PGs',
    active_listings_count: 2,
    average_rent: 11000,
    landmark_highlight: 'Near 27th Main Road',
  },
  {
    id: 'indiranagar',
    name: 'Indiranagar',
    slug: 'indiranagar',
    city_slug: 'bengaluru',
    city_name: 'Bengaluru',
    state_code: 'KA',
    state_name: 'Karnataka',
    hindi_name: 'इंदिरानगर',
    latitude: 12.9784,
    longitude: 77.6408,
    description: 'Upscale eastern Bengaluru area with metro line, vibrant dining, and boutique accommodations.',
    popular_for: 'Metro Connectivity, 100ft Road, Premium Rooms',
    active_listings_count: 0,
    average_rent: 15000,
    landmark_highlight: 'Near 12th Main Road',
  },

  // --- JAIPUR (RJ) ---
  {
    id: 'gopalpura-bypass',
    name: 'Gopalpura Bypass',
    slug: 'gopalpura-bypass',
    city_slug: 'jaipur',
    city_name: 'Jaipur',
    state_code: 'RJ',
    state_name: 'Rajasthan',
    hindi_name: 'गोपालपुरा बाईपास',
    latitude: 26.8500,
    longitude: 75.7900,
    description: 'Rajasthan premier coaching hub for RAS, REET, and engineering aspirants.',
    popular_for: 'Coaching Hubs, Libraries, Budget Hostels',
    active_listings_count: 0,
    average_rent: 5000,
    landmark_highlight: 'Gopalpura Pulia',
  },

  // --- VARANASI (UP) ---
  {
    id: 'lanka-bhu',
    name: 'Lanka (BHU Area)',
    slug: 'lanka-bhu',
    city_slug: 'varanasi',
    city_name: 'Varanasi',
    state_code: 'UP',
    state_name: 'Uttar Pradesh',
    hindi_name: 'लंका (बीएचयू)',
    latitude: 25.2800,
    longitude: 82.9990,
    description: 'Directly adjoins the historic Banaras Hindu University (BHU) main gate with extensive student facilities.',
    popular_for: 'BHU University Gate, Student Hostels, Bookshops',
    active_listings_count: 0,
    average_rent: 4500,
    landmark_highlight: 'BHU Singh Dwar',
  },
];

export const INDIAN_LANDMARKS: Landmark[] = [
  {
    id: 'au-main',
    name: 'University of Allahabad (Senate Campus)',
    short_name: 'AU Main Campus',
    category: 'university',
    city_slug: 'prayagraj',
    city_name: 'Prayagraj',
    locality: 'University Area',
    latitude: 25.4595,
    longitude: 81.8601,
    radius_km_recommended: 2.0,
  },
  {
    id: 'au-science',
    name: 'Allahabad University Science Faculty',
    short_name: 'AU Science Faculty',
    category: 'university',
    city_slug: 'prayagraj',
    city_name: 'Prayagraj',
    locality: 'Katra',
    latitude: 25.4542,
    longitude: 81.8573,
    radius_km_recommended: 1.5,
  },
  {
    id: 'mnnit',
    name: 'Motilal Nehru National Institute of Technology (MNNIT)',
    short_name: 'MNNIT Prayagraj',
    category: 'university',
    city_slug: 'prayagraj',
    city_name: 'Prayagraj',
    locality: 'Teliarganj',
    latitude: 25.4921,
    longitude: 81.8637,
    radius_km_recommended: 3.0,
  },
  {
    id: 'lu-main',
    name: 'University of Lucknow (Main Campus)',
    short_name: 'Lucknow University',
    category: 'university',
    city_slug: 'lucknow',
    city_name: 'Lucknow',
    locality: 'Hazratganj',
    latitude: 26.8650,
    longitude: 80.9380,
    radius_km_recommended: 2.5,
  },
  {
    id: 'du-north',
    name: 'Delhi University North Campus',
    short_name: 'DU North Campus',
    category: 'university',
    city_slug: 'delhi',
    city_name: 'Delhi / NCR',
    locality: 'North Campus (GTB Nagar)',
    latitude: 28.6970,
    longitude: 77.2070,
    radius_km_recommended: 2.5,
  },
  {
    id: 'iit-bombay',
    name: 'Indian Institute of Technology Bombay (IIT-B)',
    short_name: 'IIT Bombay',
    category: 'university',
    city_slug: 'mumbai',
    city_name: 'Mumbai',
    locality: 'Powai',
    latitude: 19.1334,
    longitude: 72.9133,
    radius_km_recommended: 3.0,
  },
  {
    id: 'christ-uni',
    name: 'Christ University (Main Campus)',
    short_name: 'Christ University',
    category: 'university',
    city_slug: 'bengaluru',
    city_name: 'Bengaluru',
    locality: 'Koramangala',
    latitude: 12.9344,
    longitude: 77.6060,
    radius_km_recommended: 2.5,
  },
  {
    id: 'bhu-gate',
    name: 'Banaras Hindu University (BHU Main Gate)',
    short_name: 'BHU Gate',
    category: 'university',
    city_slug: 'varanasi',
    city_name: 'Varanasi',
    locality: 'Lanka (BHU Area)',
    latitude: 25.2800,
    longitude: 82.9990,
    radius_km_recommended: 2.0,
  },
];

// Backwards compatibility aliases — now sourced from the canonical all-India dataset
import { ALL_INDIAN_LOCALITIES, ALL_INDIAN_LANDMARKS } from '../data/indiaLocations';
export const PRAYAGRAJ_LOCALITIES = ALL_INDIAN_LOCALITIES.filter((l) => l.city_slug === 'prayagraj');
export const PRAYAGRAJ_COLLEGES = ALL_INDIAN_LANDMARKS.filter((l) => l.city_slug === 'prayagraj');
