import { LocalityInfo, CollegeLandmark } from '../types';

export const PRAYAGRAJ_LOCALITIES: LocalityInfo[] = [
  {
    id: 'katra',
    name: 'Katra',
    hindi_name: 'कटरा',
    latitude: 25.4563,
    longitude: 81.8546,
    description: 'The primary student epicenter of Prayagraj. Home to book markets, coaching institutes, and affordable student rooms within walking distance of Allahabad University.',
    popular_for: 'Student PGs, University Access, Affordable Food & Messes',
    active_listings_count: 34,
    average_rent: 4800,
    landmark_highlight: 'Near AU Library Gate & Katra Chauraha',
    image_url: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'civil-lines',
    name: 'Civil Lines',
    hindi_name: 'सिविल लाइंस',
    latitude: 25.4484,
    longitude: 81.8331,
    description: 'Modern, upscale heart of Prayagraj featuring premium PGs, furnished studio flats, cafes, and major civil services coaching centers.',
    popular_for: 'Premium PGs, IAS/PCS Coaching, Cafes & Connectivity',
    active_listings_count: 26,
    average_rent: 7500,
    landmark_highlight: 'Near Subhash Chauraha & All Saints Cathedral',
    image_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'mumfordganj',
    name: 'Mumfordganj',
    hindi_name: 'ममफोर्डगंज',
    latitude: 25.4678,
    longitude: 81.8492,
    description: 'Peaceful green residential locality favored by serious civil service aspirants seeking quiet study environments.',
    popular_for: 'Quiet Study Atmosphere, Independent Rooms, Safe Environment',
    active_listings_count: 19,
    average_rent: 5500,
    landmark_highlight: 'Near Chandrashekhar Azad Park North Gate',
    image_url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'george-town',
    name: 'George Town',
    hindi_name: 'जॉर्ज टाउन',
    latitude: 25.4412,
    longitude: 81.8598,
    description: 'Centrally located leafy neighborhood close to CMP Degree College and Medical College, popular for student flats and shared rooms.',
    popular_for: 'Medical/Degree College Proximity, Tree-lined Streets',
    active_listings_count: 18,
    average_rent: 5200,
    landmark_highlight: 'Near CMP College & Sohbatiya Bagh',
    image_url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'university-area',
    name: 'University Area',
    hindi_name: 'विश्वविद्यालय क्षेत्र',
    latitude: 25.4595,
    longitude: 81.8601,
    description: 'Surrounds the historic Oxford of the East (AU Senate House, Arts and Science faculties). Maximum student concentration.',
    popular_for: 'University Gate Access, Hostels, Student Messes',
    active_listings_count: 29,
    average_rent: 4200,
    landmark_highlight: 'AU Senate Hall & Anand Bhawan Road',
    image_url: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'daraganj',
    name: 'Daraganj',
    hindi_name: 'दारागंज',
    latitude: 25.4385,
    longitude: 81.8742,
    description: 'Historic and culturally vibrant locality along the holy Ganga river with budget-friendly student accommodations.',
    popular_for: 'Budget Rooms, Riverside Walks, Traditional Atmosphere',
    active_listings_count: 14,
    average_rent: 3800,
    landmark_highlight: 'Near Shastri Bridge & Daraganj Station',
    image_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'tagore-town',
    name: 'Tagore Town',
    hindi_name: 'टैगोर टाउन',
    latitude: 25.4475,
    longitude: 81.8525,
    description: 'Prime central residential sector popular with coaching students, boasting great street food and quick transit to Civil Lines.',
    popular_for: 'Coaching Hubs, Girls Hostels, Family-Managed PGs',
    active_listings_count: 17,
    average_rent: 5800,
    landmark_highlight: 'Near Tagore Town Chauraha & Colonelganj Inter College',
    image_url: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'jhunsi',
    name: 'Jhunsi',
    hindi_name: 'झूंसी',
    latitude: 25.4328,
    longitude: 81.9056,
    description: 'Rapidly growing educational suburban hub with expansive student hostels and budget flats, connected via Shastri Bridge.',
    popular_for: 'Low Budget Accommodations, Spacious Rooms',
    active_listings_count: 11,
    average_rent: 3400,
    landmark_highlight: 'Near Andawa & GT Road',
    image_url: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'naini',
    name: 'Naini',
    hindi_name: 'नैनी',
    latitude: 25.3892,
    longitude: 81.8674,
    description: 'Major student town for agricultural, engineering, and polytechnic students studying at SHUATS and affiliated colleges.',
    popular_for: 'SHUATS Proximity, Large Campus Style PGs',
    active_listings_count: 15,
    average_rent: 4500,
    landmark_highlight: 'Near SHUATS Agriculture University Gate',
    image_url: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80',
  }
];

export const PRAYAGRAJ_COLLEGES: CollegeLandmark[] = [
  {
    id: 'au-arts',
    name: 'University of Allahabad (Senate Campus)',
    short_name: 'AU Main Campus',
    category: 'university',
    latitude: 25.4595,
    longitude: 81.8601,
    locality: 'University Area',
    radius_km_recommended: 2.0,
  },
  {
    id: 'au-science',
    name: 'Allahabad University Science Faculty',
    short_name: 'AU Science Faculty',
    category: 'university',
    latitude: 25.4542,
    longitude: 81.8573,
    locality: 'Katra',
    radius_km_recommended: 1.5,
  },
  {
    id: 'mnnit',
    name: 'Motilal Nehru National Institute of Technology (MNNIT)',
    short_name: 'MNNIT Allahabad',
    category: 'university',
    latitude: 25.4921,
    longitude: 81.8637,
    locality: 'Teliarganj',
    radius_km_recommended: 3.0,
  },
  {
    id: 'iiit-a',
    name: 'Indian Institute of Information Technology (IIIT Allahabad)',
    short_name: 'IIIT-A',
    category: 'university',
    latitude: 25.4300,
    longitude: 81.7709,
    locality: 'Jhalwa',
    radius_km_recommended: 3.5,
  },
  {
    id: 'cmp-college',
    name: 'Chaudhary Mahadeo Prasad Degree College (CMP)',
    short_name: 'CMP Degree College',
    category: 'college',
    latitude: 25.4418,
    longitude: 81.8631,
    locality: 'George Town',
    radius_km_recommended: 2.0,
  },
  {
    id: 'shuats',
    name: 'Sam Higginbottom University of Agriculture (SHUATS)',
    short_name: 'SHUATS Naini',
    category: 'university',
    latitude: 25.3905,
    longitude: 81.8681,
    locality: 'Naini',
    radius_km_recommended: 2.5,
  },
  {
    id: 'dhyeya-ias',
    name: 'Dhyeya / Drishti IAS Coaching Hub (Civil Lines)',
    short_name: 'Civil Lines Coaching Hub',
    category: 'coaching_hub',
    latitude: 25.4498,
    longitude: 81.8345,
    locality: 'Civil Lines',
    radius_km_recommended: 2.0,
  },
];
